### ISSUE TITLE
Meteor REST API for account system

### ISSUE THREAD

**Issue by gaetandezeiraud** [aadamsx/fine-rest#1]
I want to use your module with Meteor. I have 2 different websites, one of this is the "main website" with account and the other a service. I want the possibility to the user to connect on the website 2 with the main account, of the main website.

I saw your example, and i think understand the code for the main website. But, how use the token and create the account on the service website ? With just 'accounts-base' ? I have take a look at how the Google+ API works, but I'm having trouble seeing how this is implemented, and implementing this for my own sites. Similar system.

Thank you for your answer, hoping that you can enlighten me.

**Comment by aadamsx** [comment]
> I saw your example, and i think understand the code for the main website. But, how use the token and create the account on the service website ?

Are you talking about the Bearer token?

Also, I'm working on making a token login system, instead of the username/password system in place now.  I'll update this repo with the new tech and add examples on how to use it when I'm done, so stay tuned.

**Comment by gaetandezeiraud** [comment]
Hi, 
Thanks for your awnser!
"Are you talking about the Bearer token?" - For example, yes, I don't know why use it for create account on my other website? I think it's a logic problem in my head and the solution, it's very easy but... I have trouble.

"Also, I'm working on making a token login system" - Very good functionality! I would therefore be attentive.

**Comment by aadamsx** [comment]
Right, so the Bearer token is received (currently) when you using the ```/user/login``` route, and afterwards all calls from the client to the routes you make in JsonRoutes should use this token to make sure you're authorized.  You'll pass in the Bearer via the header.

But you need to make sure you put in the JsonRoutes middleware to check that the call is authorized, the example code I have provided in this repo: https://github.com/aadamsx/meteor-web-app-test should show you how to do this.

I'm working on a system now where instead of passing in username and password to get your Bearer token, you'll pass in a temporary token instead.  That's coming soon.

I hope this helps.

**Comment by gaetandezeiraud** [comment]
Hi, 
Thanks for your awnser, i understand the Bearer system and effectively, It doesn't correspond of the system i need. (Simple Token account system like Google+ or Twitter).

I will watch your future implementation of the token closely because it interests me strongly.
Thanks for his detailed answers!

**Comment by aadamsx** [comment]
I just updated this lib to include a new way to auth.  Instead of using username/password to auth, you can now use a token system -- just pass a token over the /users/token-login endpoint to auth, and it will return a Bearer token you can store somewhere for subsequent calls to the Web API.  Once the Web API has validated the token, it will dispose of the simple token (or loginToken) and return you a Bearer token that's more "permanent".

The example repo shows how to use the new token mechanism. 

I'm not sure how this compares to the "Simple Token account system" you're referrring to.  This is a simple token passed over the endpoint to auth -- so it might be the same thing.
